### ISSUE TITLE
Missing info in amavis av_scanners command

### ISSUE THREAD

**Issue by camaer** [iredmail/iRedMail#82]
- iRedMail version (check /etc/iredmail-release): 1.3.1
- Deployed with iRedMail Easy or the downloadable installer? Downloadable installer
- Linux/BSD distribution name and version:  Ubuntu 20.04
- Store mail accounts in which backend (LDAP/MySQL/PGSQL):  PGSQL
- Web server (Apache or Nginx): Nginx
- Manage mail accounts with iRedAdmin-Pro? Yes
- [IMPORTANT] Related original log or error message is required if you're experiencing an issue.
----

In the amavisd config we are deploying, there is an issue with the *@av_scanner* section.

Here's what we are deploying:

```
@av_scanners = (
    ['clamav-socket',
    \&ask_daemon, ["CONTSCAN {}\n", 'PH_CLAMD_LOCAL_SOCKET'],
    qr/\bOK$/, qr/\bFOUND$/,
    qr/^.*?: (?!Infected Archive)(.*) FOUND$/ ],
);
```

The issue if there is a virus flagged, we don't know from which database it matches. Note the empty *()* after Infected.
```
Blocked INFECTED () {DiscardedInternal,Quarantined}, MYNETS LOCA
L [127.0.0.1]:48820 ESMTP/ESMTP
```

If we change *@av_scanners* for the following:
```
@av_scanners = (
    ['clamav-socket',
    \&ask_daemon, ["CONTSCAN {}\n", 'PH_CLAMD_LOCAL_SOCKET'],
    qr/\bOK$/m, qr/\bFOUND$/m,
    qr/^.*?: (?!Infected Archive)(.*) FOUND$/m ],
);
```

Then we get more info on the virus. Especially which database it's from: 
```
Blocked INFECTED (SecuriteInfo.com.Eicar-Test-Signature-2.UNOFFI
CIAL) {DiscardedInternal,Quarantined}, MYNETS LOCAL [127.0.0.1]:49250 ESM
```

This reflect in the logs but also in iredadminpro in the Quarantine section

<img width="432" alt="Screen Shot 2020-09-09 at 10 19 23 AM" src="https://user-images.githubusercontent.com/35572989/92610703-031d1b00-f286-11ea-9a52-f45bb9d640d5.png">
<img width="659" alt="Screen Shot 2020-09-09 at 10 19 34 AM" src="https://user-images.githubusercontent.com/35572989/92610715-06b0a200-f286-11ea-84ea-1d4536b94cad.png">

**Comment by iredmail** [comment]
- Did you deploy with the downloadable iRedMail-1.3.1 installer? Or the git version?
- With iRedMail-1.3.1, the placeholder `PH_CLAMD_LOCAL_SOCKET` in Amavisd config file `/etc/amavis/conf.d/50-user` is correctly replaced by the socket path `/var/run/clamav/clamd.ctl`. Or are we talking about another issue?

**Comment by camaer** [comment]
The server was installed using the iRedMail 1.3.1 installer.

Sorry about the confusion. I've originally copied my working config but it should be PH_CLAMD_LOCAL_SOCKET. I've edited my original post.

The issue appear when there is no `m` after `qr/\bOK$/`, `qr/\bOK$/` and `qr/\bOK$/`

**Comment by iredmail** [comment]
Thanks for the feedback. Fixed in latest commit.

**Comment by camaer** [comment]
No problem. Seems like you forgot the `m` after the FOUND on line 385. The line should be like so:

```
qr/^.*?: (?!Infected Archive)(.*) FOUND$/m ],
```

**Comment by iredmail** [comment]
Fixed before your reply. :)
